<?php

namespace Winter\Matomo\Classes;

use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Winter\Matomo\Classes\Exceptions\MatomoAuthenticationException;
use Winter\Matomo\Classes\Exceptions\MatomoConfigurationException;
use Winter\Matomo\Classes\Exceptions\MatomoReportingException;
use Winter\Matomo\Classes\Exceptions\MatomoRequestTimeoutException;
use Winter\Matomo\Classes\Exceptions\MatomoServerException;

/**
 * Matomo Reporting API service.
 */
class MatomoReportingService
{
    /**
     * Cache key used to keep track of generated request keys.
     */
    private const CACHE_INDEX_KEY = 'winter.matomo.report.cache_keys';

    /**
     * Cache prefix for reporting API responses.
     */
    private const CACHE_PREFIX = 'winter.matomo.report.';

    /**
     * API endpoint to the Matomo index.php file.
     */
    protected string $endpointUrl;

    /**
     * Matomo auth token.
     */
    protected string $authToken;

    /**
     * Matomo site identifier.
     */
    protected int $siteId;

    /**
     * Reporting cache TTL in seconds.
     */
    protected int $cacheTtl;

    /**
     * HTTP timeout in seconds.
     */
    protected int $httpTimeout;

    /**
     * Whether to verify SSL certificates.
     */
    protected bool $verifySsl;

    public function __construct(
        string $serverUrl,
        ?string $authToken,
        int $siteId,
        int $cacheTtl = 900,
        int $httpTimeout = 10,
        bool $verifySsl = true
    ) {
        $this->endpointUrl = rtrim($serverUrl, '/') . '/index.php';
        $this->authToken = trim((string) $authToken);
        $this->siteId = $siteId;
        $this->cacheTtl = max(1, $cacheTtl);
        $this->httpTimeout = max(1, $httpTimeout);
        $this->verifySsl = $verifySsl;
    }

    /**
     * Executes a single Matomo Reporting API method call.
     */
    public function get(string $method, array $params = []): array
    {
        $payload = array_merge($params, [
            'module' => 'API',
            'method' => $method,
            'idSite' => $this->siteId,
            'format' => 'json',
            'token_auth' => $this->authToken,
        ]);

        return $this->request($payload);
    }

    /**
     * Executes a Matomo bulk request with API.getBulkRequest.
     */
    public function bulk(array $requests): array
    {
        $bulkUrls = [];

        foreach ($requests as $request) {
            if (!is_array($request) || empty($request['method'])) {
                throw new MatomoReportingException('Each bulk request must include a "method" key.');
            }

            $requestPayload = array_merge($request, [
                'module' => 'API',
                'idSite' => $this->siteId,
                'format' => 'json',
            ]);

            $bulkUrls[] = '?' . http_build_query($requestPayload, '', '&', PHP_QUERY_RFC3986);
        }

        return $this->request([
            'module' => 'API',
            'method' => 'API.getBulkRequest',
            'format' => 'json',
            'token_auth' => $this->authToken,
            'urls' => $bulkUrls,
        ]);
    }

    /**
     * Clears only cache entries generated by this service.
     */
    public function clearCache(): void
    {
        $keys = Cache::get(static::CACHE_INDEX_KEY, []);

        foreach ($keys as $key) {
            Cache::forget($key);
        }

        Cache::forget(static::CACHE_INDEX_KEY);
    }

    /**
     * Executes a request with caching and typed exception handling.
     */
    protected function request(array $payload): array
    {
        $this->validateConfiguration($payload);

        $cacheKey = static::CACHE_PREFIX . md5(json_encode($this->normalizeForHash($payload)));
        $this->rememberCacheKey($cacheKey);

        return Cache::remember($cacheKey, $this->cacheTtl, function () use ($payload) {
            $safeContext = $this->buildSafeContext($payload);

            try {
                $httpClient = Http::asForm()
                    ->timeout($this->httpTimeout)
                    ->acceptJson();

                if (!$this->verifySsl) {
                    $httpClient = $httpClient->withoutVerifying();
                }

                $response = $httpClient->post($this->endpointUrl, $payload);
            } catch (ConnectionException $exception) {
                $connectionError = $this->classifyConnectionError($exception);
                $connectionContext = $safeContext + [
                    'connection_error' => $connectionError,
                    'host' => $this->endpointHost(),
                    'exception' => $exception->getMessage(),
                ];

                $logMessage = match ($connectionError) {
                    'dns_resolution' => 'Matomo reporting request failed: host could not be resolved.',
                    'connection_refused' => 'Matomo reporting request failed: connection was refused.',
                    'timeout' => 'Matomo reporting request timed out.',
                    'ssl_certificate' => 'Matomo reporting request failed: SSL certificate verification failed.',
                    default => 'Matomo reporting request timed out or connection failed.',
                };

                Log::warning($logMessage, $connectionContext);

                throw new MatomoRequestTimeoutException(
                    $logMessage,
                    $connectionContext,
                    0,
                    $exception
                );
            } catch (\Throwable $exception) {
                Log::error('Matomo reporting request failed before receiving a response.', $safeContext + [
                    'exception' => $exception->getMessage(),
                ]);

                throw new MatomoServerException(
                    'Matomo request failed before receiving a response.',
                    $safeContext,
                    0,
                    $exception
                );
            }

            if ($response->status() === 401) {
                Log::warning('Matomo authentication failed for reporting request.', $safeContext + [
                    'status' => 401,
                ]);

                throw new MatomoAuthenticationException(
                    'Matomo authentication failed. Verify your token configuration.',
                    $safeContext + ['status' => 401]
                );
            }

            if (!$response->successful()) {
                Log::error('Matomo API returned a non-successful response status.', $safeContext + [
                    'status' => $response->status(),
                ]);

                throw new MatomoServerException(
                    'Matomo API returned an unexpected response status: ' . $response->status(),
                    $safeContext + ['status' => $response->status()]
                );
            }

            $data = $response->json();
            if (!is_array($data)) {
                Log::error('Matomo API response could not be parsed as JSON.', $safeContext);

                throw new MatomoServerException(
                    'Matomo API response could not be parsed as JSON.',
                    $safeContext
                );
            }

            if (($data['result'] ?? null) === 'error') {
                $message = (string) ($data['message'] ?? 'Unknown Matomo API error.');

                if (stripos($message, 'token') !== false || stripos($message, 'authentication') !== false) {
                    Log::warning('Matomo API returned an authentication error payload.', $safeContext + [
                        'api_message' => $message,
                    ]);

                    throw new MatomoAuthenticationException(
                        'Matomo authentication failed. Verify your token configuration.',
                        $safeContext + ['api_message' => $message]
                    );
                }

                Log::warning('Matomo API returned a reporting error payload.', $safeContext + [
                    'api_message' => $message,
                ]);

                throw new MatomoReportingException(
                    'Matomo API error: ' . $message,
                    $safeContext + ['api_message' => $message]
                );
            }

            return $data;
        });
    }

    /**
     * Validates the current service configuration before sending requests.
     *
     * @param array<string, mixed> $payload
     */
    protected function validateConfiguration(array $payload): void
    {
        $safeContext = $this->buildSafeContext($payload);

        if ($this->siteId <= 0) {
            Log::warning('Matomo reporting configuration is invalid: site id must be positive.', $safeContext);

            throw new MatomoConfigurationException(
                'Matomo configuration invalid: site id must be greater than 0.',
                $safeContext
            );
        }

        if ($this->authToken === '') {
            Log::warning('Matomo reporting configuration is invalid: auth token is missing.', $safeContext);

            throw new MatomoConfigurationException(
                'Matomo configuration invalid: auth token is missing.',
                $safeContext
            );
        }

        $scheme = (string) parse_url($this->endpointUrl, PHP_URL_SCHEME);
        $isValidUrl = filter_var($this->endpointUrl, FILTER_VALIDATE_URL) !== false;

        if (!$isValidUrl || !in_array($scheme, ['http', 'https'], true)) {
            Log::warning('Matomo reporting configuration is invalid: server URL is malformed.', $safeContext + [
                'endpoint' => $this->endpointUrl,
            ]);

            throw new MatomoConfigurationException(
                'Matomo configuration invalid: server URL must be a valid http(s) URL.',
                $safeContext + ['endpoint' => $this->endpointUrl]
            );
        }
    }

    /**
     * Builds a safe context array that excludes secrets.
     *
     * @param array<string, mixed> $payload
     * @return array<string, mixed>
     */
    protected function buildSafeContext(array $payload): array
    {
        $safePayload = $payload;
        unset($safePayload['token_auth']);

        return [
            'endpoint' => $this->endpointUrl,
            'site_id' => $this->siteId,
            'timeout' => $this->httpTimeout,
            'payload' => $safePayload,
        ];
    }

    /**
     * Stores request cache keys so clearCache can invalidate them safely.
     */
    protected function rememberCacheKey(string $cacheKey): void
    {
        $keys = Cache::get(static::CACHE_INDEX_KEY, []);

        if (in_array($cacheKey, $keys, true)) {
            return;
        }

        $keys[] = $cacheKey;
        Cache::forever(static::CACHE_INDEX_KEY, $keys);
    }

    /**
     * Sorts payload recursively to ensure deterministic cache key hashes.
     */
    protected function normalizeForHash(array $payload): array
    {
        foreach ($payload as $key => $value) {
            if (is_array($value)) {
                $payload[$key] = $this->normalizeForHash($value);
            }
        }

        ksort($payload);

        return $payload;
    }

    /**
     * Returns the hostname parsed from the configured endpoint.
     */
    protected function endpointHost(): ?string
    {
        $host = parse_url($this->endpointUrl, PHP_URL_HOST);

        if (!is_string($host) || $host === '') {
            return null;
        }

        return $host;
    }

    /**
     * Maps low-level connection exceptions to stable error categories.
     */
    protected function classifyConnectionError(ConnectionException $exception): string
    {
        $message = strtolower($exception->getMessage());

        if (str_contains($message, 'could not resolve host')) {
            return 'dns_resolution';
        }

        if (str_contains($message, 'connection refused')) {
            return 'connection_refused';
        }

        if (str_contains($message, 'timed out')) {
            return 'timeout';
        }

        if (str_contains($message, 'ssl certificate') || str_contains($message, 'ssl: certificate') || str_contains($message, 'unable to get local issuer certificate')) {
            return 'ssl_certificate';
        }

        return 'connection_failed';
    }
}
