<?php

namespace Winter\Matomo\Classes;

use Illuminate\Http\Client\ConnectionException;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Winter\Matomo\Classes\Exceptions\MatomoAuthenticationException;
use Winter\Matomo\Classes\Exceptions\MatomoConfigurationException;
use Winter\Matomo\Classes\Exceptions\MatomoReportingException;
use Winter\Matomo\Classes\Exceptions\MatomoRequestTimeoutException;
use Winter\Matomo\Classes\Exceptions\MatomoServerException;

/**
 * Matomo Reporting API service.
 */
class MatomoReportingService
{
    /**
     * Cache key used to keep track of generated request keys.
     */
    private const CACHE_INDEX_KEY = 'winter.matomo.report.cache_keys';

    /**
     * Cache prefix for reporting API responses.
     */
    private const CACHE_PREFIX = 'winter.matomo.report.';

    /**
     * API endpoint to the Matomo index.php file.
     */
    protected string $endpointUrl;

    /**
     * Matomo auth token.
     */
    protected string $authToken;

    /**
     * Matomo site identifier.
     */
    protected int $siteId;

    /**
     * Reporting cache TTL in seconds.
     */
    protected int $cacheTtl;

    /**
     * HTTP timeout in seconds.
     */
    protected int $httpTimeout;

    /**
     * Whether to verify SSL certificates.
     */
    protected bool $verifySsl;

    public function __construct(
        string $serverUrl,
        ?string $authToken,
        int $siteId,
        int $cacheTtl = 900,
        int $httpTimeout = 10,
        bool $verifySsl = true
    ) {
        $this->endpointUrl = rtrim($serverUrl, '/') . '/index.php';
        $this->authToken = trim((string) $authToken);
        $this->siteId = $siteId;
        $this->cacheTtl = max(1, $cacheTtl);
        $this->httpTimeout = max(1, $httpTimeout);
        $this->verifySsl = $verifySsl;
    }

    /**
     * Executes a single Matomo Reporting API method call.
     * Optional $scope can be provided to group cache entries (e.g., 'TopPages' for widget-scoped cache invalidation).
     */
    public function get(string $method, array $params = [], ?string $scope = null): array
    {
        $payload = array_merge($params, [
            'module' => 'API',
            'method' => $method,
            'idSite' => $this->siteId,
            'format' => 'json',
            'token_auth' => $this->authToken,
        ]);

        return $this->request($payload, $scope);
    }

    /**
     * Executes a Matomo bulk request with API.getBulkRequest.
     */
    public function bulk(array $requests): array
    {
        $bulkUrls = [];

        foreach ($requests as $request) {
            if (!is_array($request) || empty($request['method'])) {
                throw new MatomoReportingException('Each bulk request must include a "method" key.');
            }

            $requestPayload = array_merge($request, [
                'module' => 'API',
                'idSite' => $this->siteId,
                'format' => 'json',
            ]);

            $bulkUrls[] = http_build_query($requestPayload, '', '&', PHP_QUERY_RFC3986);
        }

        return $this->request([
            'module' => 'API',
            'method' => 'API.getBulkRequest',
            'format' => 'json',
            'token_auth' => $this->authToken,
            'urls' => $bulkUrls,
        ]);
    }

    /**
     * Clears cache entries generated by this service.
     * If $identifier is provided, only entries matching that identifier are cleared.
     * If $identifier is null, all cache entries are cleared.
     */
    public function clearCache(?string $identifier = null): void
    {
        $this->withCacheIndexLock(function () use ($identifier): void {
            $cacheIndex = $this->pruneExpiredIndexEntries(Cache::get(self::CACHE_INDEX_KEY, []));

            if (empty($cacheIndex)) {
                Cache::forget(self::CACHE_INDEX_KEY);

                return;
            }

            if ($identifier === null || $identifier === '') {
                // Clear all caches
                foreach ($cacheIndex as $entry) {
                    $cacheKey = is_array($entry) ? $entry['key'] : $entry;
                    Cache::forget($cacheKey);
                }

                Cache::forget(self::CACHE_INDEX_KEY);

                return;
            }

            // Clear only caches matching the identifier
            $normalizedIdentifier = $this->normalizeCacheIdentifier($identifier);
            $remainingEntries = [];

            foreach ($cacheIndex as $entry) {
                if (!is_array($entry)) {
                    if (is_string($entry) && str_starts_with($entry, $normalizedIdentifier)) {
                        Cache::forget($entry);
                        continue;
                    }

                    if (is_string($entry)) {
                        $remainingEntries[] = $entry;
                    }

                    continue;
                }

                $entryIdentifier = (string) ($entry['identifier'] ?? $entry['key'] ?? '');
                $entryKey = (string) ($entry['key'] ?? '');

                if ($entryKey !== '' && str_starts_with($entryIdentifier, $normalizedIdentifier)) {
                    // This entry matches the identifier prefix, forget it.
                    Cache::forget($entryKey);
                    continue;
                }

                $remainingEntries[] = $entry;
            }

            // Update the index only if there are remaining entries
            if (!empty($remainingEntries)) {
                Cache::forever(self::CACHE_INDEX_KEY, $remainingEntries);
            } else {
                Cache::forget(self::CACHE_INDEX_KEY);
            }
        });
    }

    /**
     * Returns the canonical cache identifier for a GET request method and params.
     *
     * @param array<string, mixed> $params
     */
    public function getCacheIdentifier(string $method, array $params = [], ?string $scope = null): string
    {
        $payload = array_merge($params, [
            'module' => 'API',
            'method' => $method,
            'idSite' => $this->siteId,
            'format' => 'json',
            'token_auth' => $this->authToken,
        ]);

        return $this->buildCacheIdentifier($method, $payload, $scope);
    }

    /**
     * Executes a request with caching and typed exception handling.
     * Optional $scope is used to generate widget-scoped cache identifiers for granular invalidation.
     */
    protected function request(array $payload, ?string $scope = null): array
    {
        $this->validateConfiguration($payload);

        $method = (string) ($payload['method'] ?? 'request');
        $identifier = $this->buildCacheIdentifier($method, $payload, $scope);
        $cacheKey = $identifier;

        $this->rememberCacheKey($cacheKey, $identifier);

        return Cache::remember($cacheKey, $this->cacheTtl, function () use ($payload) {
            $safeContext = $this->buildSafeContext($payload);

            try {
                $httpClient = Http::asForm()
                    ->timeout($this->httpTimeout)
                    ->acceptJson();

                if (!$this->verifySsl) {
                    $httpClient = $httpClient->withoutVerifying();
                }

                $response = $httpClient->post($this->endpointUrl, $payload);
            } catch (ConnectionException $exception) {
                $connectionError = $this->classifyConnectionError($exception);
                $connectionContext = $safeContext + [
                    'connection_error' => $connectionError,
                    'host' => $this->endpointHost(),
                    'exception' => $exception->getMessage(),
                ];

                $logMessage = match ($connectionError) {
                    'dns_resolution' => 'Matomo reporting request failed: host could not be resolved.',
                    'connection_refused' => 'Matomo reporting request failed: connection was refused.',
                    'timeout' => 'Matomo reporting request timed out.',
                    'ssl_certificate' => 'Matomo reporting request failed: SSL certificate verification failed.',
                    default => 'Matomo reporting request timed out or connection failed.',
                };

                Log::warning($logMessage, $connectionContext);

                throw new MatomoRequestTimeoutException(
                    $logMessage,
                    $connectionContext,
                    0,
                    $exception
                );
            } catch (\Throwable $exception) {
                Log::error('Matomo reporting request failed before receiving a response.', $safeContext + [
                    'exception' => $exception->getMessage(),
                ]);

                throw new MatomoServerException(
                    'Matomo request failed before receiving a response.',
                    $safeContext,
                    0,
                    $exception
                );
            }

            if ($response->status() === 401) {
                Log::warning('Matomo authentication failed for reporting request.', $safeContext + [
                    'status' => 401,
                ]);

                throw new MatomoAuthenticationException(
                    'Matomo authentication failed. Verify your token configuration.',
                    $safeContext + ['status' => 401]
                );
            }

            if (!$response->successful()) {
                Log::error('Matomo API returned a non-successful response status.', $safeContext + [
                    'status' => $response->status(),
                ]);

                throw new MatomoServerException(
                    'Matomo API returned an unexpected response status: ' . $response->status(),
                    $safeContext + ['status' => $response->status()]
                );
            }

            $data = $response->json();
            if (!is_array($data)) {
                Log::error('Matomo API response could not be parsed as JSON.', $safeContext);

                throw new MatomoServerException(
                    'Matomo API response could not be parsed as JSON.',
                    $safeContext
                );
            }

            if (($data['result'] ?? null) === 'error') {
                $message = (string) ($data['message'] ?? 'Unknown Matomo API error.');

                if (stripos($message, 'token') !== false || stripos($message, 'authentication') !== false) {
                    Log::warning('Matomo API returned an authentication error payload.', $safeContext + [
                        'api_message' => $message,
                    ]);

                    throw new MatomoAuthenticationException(
                        'Matomo authentication failed. Verify your token configuration.',
                        $safeContext + ['api_message' => $message]
                    );
                }

                Log::warning('Matomo API returned a reporting error payload.', $safeContext + [
                    'api_message' => $message,
                ]);

                throw new MatomoReportingException(
                    'Matomo API error: ' . $message,
                    $safeContext + ['api_message' => $message]
                );
            }

            return $data;
        });
    }

    /**
     * Validates the current service configuration before sending requests.
     *
     * @param array<string, mixed> $payload
     */
    protected function validateConfiguration(array $payload): void
    {
        $safeContext = $this->buildSafeContext($payload);

        if ($this->siteId <= 0) {
            Log::warning('Matomo reporting configuration is invalid: site id must be positive.', $safeContext);

            throw new MatomoConfigurationException(
                'Matomo configuration invalid: site id must be greater than 0.',
                $safeContext
            );
        }

        if ($this->authToken === '') {
            Log::warning('Matomo reporting configuration is invalid: auth token is missing.', $safeContext);

            throw new MatomoConfigurationException(
                'Matomo configuration invalid: auth token is missing.',
                $safeContext
            );
        }

        $scheme = (string) parse_url($this->endpointUrl, PHP_URL_SCHEME);
        $isValidUrl = filter_var($this->endpointUrl, FILTER_VALIDATE_URL) !== false;

        if (!$isValidUrl || !in_array($scheme, ['http', 'https'], true)) {
            Log::warning('Matomo reporting configuration is invalid: server URL is malformed.', $safeContext + [
                'endpoint' => $this->endpointUrl,
            ]);

            throw new MatomoConfigurationException(
                'Matomo configuration invalid: server URL must be a valid http(s) URL.',
                $safeContext + ['endpoint' => $this->endpointUrl]
            );
        }
    }

    /**
     * Builds a safe context array that excludes secrets.
     *
     * @param array<string, mixed> $payload
     * @return array<string, mixed>
     */
    protected function buildSafeContext(array $payload): array
    {
        $safePayload = $payload;
        unset($safePayload['token_auth']);

        return [
            'endpoint' => $this->endpointUrl,
            'site_id' => $this->siteId,
            'timeout' => $this->httpTimeout,
            'payload' => $safePayload,
        ];
    }

    /**
     * Stores request cache keys with identifiers for granular cache invalidation.
     */
    protected function rememberCacheKey(string $cacheKey, string $identifier): void
    {
        $this->withCacheIndexLock(function () use ($cacheKey, $identifier): void {
            $cacheIndex = $this->pruneExpiredIndexEntries(Cache::get(self::CACHE_INDEX_KEY, []));

            // Check if this exact cache key already exists
            foreach ($cacheIndex as $entry) {
                if (is_array($entry) && $entry['key'] === $cacheKey) {
                    return;
                }
            }

            $cacheIndex[] = [
                'key' => $cacheKey,
                'identifier' => $identifier,
                'expires_at' => time() + $this->cacheTtl,
            ];

            Cache::forever(self::CACHE_INDEX_KEY, $cacheIndex);
        });
    }

    /**
     * Removes index entries whose underlying cache entry has already expired.
     *
     * @param array<int, mixed> $cacheIndex
     * @return array<int, mixed>
     */
    protected function pruneExpiredIndexEntries(array $cacheIndex): array
    {
        $now = time();

        return array_values(array_filter($cacheIndex, function ($entry) use ($now): bool {
            // Legacy string entries have no expiry metadata, keep them until explicitly cleared.
            if (!is_array($entry) || !isset($entry['expires_at'])) {
                return true;
            }

            return (int) $entry['expires_at'] > $now;
        }));
    }

    /**
     * Builds the canonical scoped cache identifier for one payload.
     *
     * @param array<string, mixed> $payload
     */
    protected function buildCacheIdentifier(string $method, array $payload, ?string $scope = null): string
    {
        $identifierScope = ($scope !== null && $scope !== '')
            ? $scope . ':' . $method
            : $method;

        return $this->normalizeCacheIdentifier($identifierScope)
            . md5(json_encode($this->normalizeForHash($payload)));
    }

    /**
     * Normalizes a method name or raw identifier to the canonical cache prefix.
     */
    protected function normalizeCacheIdentifier(string $identifier): string
    {
        if (str_starts_with($identifier, self::CACHE_PREFIX)) {
            return $identifier;
        }

        return self::CACHE_PREFIX . trim($identifier, '.') . '.';
    }

    /**
     * Executes a callback while holding a cache-index lock when supported.
     */
    protected function withCacheIndexLock(callable $callback): void
    {
        $store = Cache::getStore();

        if (method_exists($store, 'lock')) {
            Cache::lock(self::CACHE_INDEX_KEY . '.lock', 10)->block(5, function () use ($callback): void {
                $callback();
            });

            return;
        }

        $callback();
    }

    /**
     * Sorts payload recursively to ensure deterministic cache key hashes.
     */
    protected function normalizeForHash(array $payload): array
    {
        foreach ($payload as $key => $value) {
            if (is_array($value)) {
                $payload[$key] = $this->normalizeForHash($value);
            }
        }

        ksort($payload);

        return $payload;
    }

    /**
     * Returns the hostname parsed from the configured endpoint.
     */
    protected function endpointHost(): ?string
    {
        $host = parse_url($this->endpointUrl, PHP_URL_HOST);

        if (!is_string($host) || $host === '') {
            return null;
        }

        return $host;
    }

    /**
     * Maps low-level connection exceptions to stable error categories.
     */
    protected function classifyConnectionError(ConnectionException $exception): string
    {
        $message = strtolower($exception->getMessage());

        if (str_contains($message, 'could not resolve host')) {
            return 'dns_resolution';
        }

        if (str_contains($message, 'connection refused')) {
            return 'connection_refused';
        }

        if (str_contains($message, 'timed out')) {
            return 'timeout';
        }

        if (str_contains($message, 'ssl certificate') || str_contains($message, 'ssl: certificate') || str_contains($message, 'unable to get local issuer certificate')) {
            return 'ssl_certificate';
        }

        return 'connection_failed';
    }
}
